apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobprocessor.fullname" . }}-api
  labels:
    {{- include "jobprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "jobprocessor.fullname" . }}-api-tls
spec:
  selector:
    {{- include "jobprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: https
      port: 8000
      targetPort: 8000
