apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "jobprocessor.fullname" . }}-api
  labels:
    {{- include "jobprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  to:
    kind: Service
    name: {{ include "jobprocessor.fullname" . }}-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
