apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobprocessor.fullname" . }}-postgres
  labels:
    {{- include "jobprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "jobprocessor.fullname" . }}-postgres-tls
spec:
  clusterIP: None
  selector:
    {{- include "jobprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
